## DSO109 - Programming Foundations - Python
### Lesson 9 - NumPy
______________

#### Page 13 - Hands-On

Please complete the following tasks in a Jupyter Notebook file, using the numpy package:

* **Create a five element array using your favorite numbers named myFavorites.**

In [3]:
import numpy as np

In [4]:
myFavorites = np.array([8,11,35,14,4])

In [5]:
myFavorites

array([ 8, 11, 35, 14,  4])

__________
* **Perform each of the five aggregate functions on your array.**

In [6]:
myFavorites.max()

35

In [7]:
myFavorites.mean()

14.4

In [8]:
myFavorites.min()

4

In [9]:
myFavorites.std()

10.818502669038818

In [10]:
myFavorites.sum()

72

__________
* **Create a five element array containing only ones named `OneArrayToRuleThemAll`.**

In [12]:
OneArrayToRuleThemAll = np.ones(5)

In [13]:
OneArrayToRuleThemAll

array([1., 1., 1., 1., 1.])

__________
* **Add `myFavorites` and `OneArrayToRuleThemAll`.**

In [14]:
myFavorites + OneArrayToRuleThemAll

array([ 9., 12., 36., 15.,  5.])

__________
* **Multiply every element in `myFavorites` by two.**

In [15]:
myFavorites * 2

array([16, 22, 70, 28,  8])

__________
* **Call the third element in `myFavorites` using indexing.**

In [16]:
myFavorites[2]

35

__________
* **Create a four element, two-by-two matrix of numbers named `TheMatrixHasYou`.**

In [17]:
TheMatrixHasYou = np.array([[1, 2], [3, 4]])

In [18]:
TheMatrixHasYou

array([[1, 2],
       [3, 4]])

__________
* **Access the upper left element in `TheMatrixHasYou` using indexing.**

In [19]:
TheMatrixHasYou[0, 0]

1

__________
* **Find the largest number in each row for `TheMatrixHasYou`.**

In [20]:
TheMatrixHasYou.max(axis=1)

array([2, 4])

__________
* **Reshape `TheMatrixHasYou` into a matrix with one row and four columns.**

In [22]:
TheMatrixHasYou.reshape(1,4)

array([[1, 2, 3, 4]])