## DSO109 - Programming Foundations - Python
### Lesson 9 - NumPy
______________

#### Page 1 - Introduction

______________
***From Workshop***

**Import packages**

In [1]:
import numpy as np

**Create a 5 element array**

In [2]:
array5 = np.array([7, 2, 1, 4, 9])

In [3]:
array5

array([7, 2, 1, 4, 9])

**Aggregate functions**

In [4]:
array5.min()

1

In [5]:
array5.max()

9

In [6]:
array5.sum()

23

In [7]:
array5.mean()

4.6

In [8]:
array5.std()

3.006659275674582

**Create an array of only 1's**

In [9]:
the1s = np.ones(5)

In [10]:
the1s

array([1., 1., 1., 1., 1.])

*Note: why on earth is this a function ?!*

**Add arrays together**

In [11]:
array5 + the1s

array([ 8.,  3.,  2.,  5., 10.])

**Multiply array by 4**

In [12]:
array5 *4

array([28,  8,  4, 16, 36])

**Call the 4th element using indexing**

In [13]:
array5[3]

4

**Create an 8 element, 4x2 matrix**

In [14]:
matrixMeCrazy = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [15]:
matrixMeCrazy

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Access the bottom right element**

In [16]:
matrixMeCrazy[1,3]

8

**Reshape the matrix to 2x4**

In [17]:
matrixMeCrazy.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

***Reshape again***

In [18]:
matrixMeCrazy.reshape(8, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

***Reshape to get an error***

In [19]:
# matrixMeCrazy.reshape(4, 1)

*Commented out after receiving error:*

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/zg/fxyw2v_910lgtrr94rf2vw0c0000gs/T/ipykernel_42939/2157460842.py in <module>
----> 1 matrixMeCrazy.reshape(4, 1)

ValueError: cannot reshape array of size 8 into shape (4,1)

______________

#### Page 2 - NumPy Arrays

In [20]:
import numpy as np

In [21]:
myArray = np.array([7, 2, 1])

In [22]:
myArray

array([7, 2, 1])

In [23]:
print(myArray)

[7 2 1]


______________

#### Page 3 - Aggregate Functions on Arrays

**.max() function**

In [24]:
myArray.max()

7

**.min() function**

In [25]:
myArray.min()

1

**.mean() function**

In [26]:
myArray.mean()

3.3333333333333335

**.std() function**

In [27]:
myArray.std()

2.6246692913372702

**.sum(max) function**

In [28]:
myArray.sum()

10

____________
#### Page 4 - Data Generation with NumPy

**Generating Random Numbers**

In [29]:
randomNums = np.random.random(1)

In [30]:
randomNums

array([0.40305355])

**Generating Specific Numbers**

In [31]:
all1s = np.ones(7)

In [32]:
all1s

array([1., 1., 1., 1., 1., 1., 1.])

In [33]:
all0s = np.zeros(2)

In [34]:
all0s

array([0., 0.])

___________
#### Page 5 - Arithmetic with Arrays

**Arithmetic with 2 arrays**

In [35]:
my2ndArray = np.array([1, 2, 7])

***Adding***

In [36]:
myArray + my2ndArray

array([8, 4, 8])

*If you're feeling doubtful, try it longhand yourself once. my_first_array contains the values 7, 2, and 1. my_second_array contains the values 1, 2, and 7. So, 7 (from the first array) plus 1 (from the second array) is 8. Similarly, 2 from the first array and 2 from the second array make 4. Lastly, 1 from the first array and 7 from the second array added together make 8 once more.*

In [37]:
arraySummed = myArray + my2ndArray

In [38]:
arraySummed

array([8, 4, 8])

***Subtracting***

In [39]:
arraySubtracted = myArray - my2ndArray

In [40]:
arraySubtracted

array([ 6,  0, -6])

***Multiplying***

In [41]:
arrayMultiplied = myArray * my2ndArray

In [42]:
arrayMultiplied

array([7, 4, 7])

***Dividing***

In [43]:
arrayDivided = myArray / my2ndArray

In [44]:
arrayDivided

array([7.        , 1.        , 0.14285714])

**Arithmetic on 1 array**

***Multiplying***

In [45]:
times4 = myArray * 4

In [46]:
times4

array([28,  8,  4])

***Dividing***

In [47]:
dividedBy4 = myArray / 4

In [48]:
dividedBy4

array([1.75, 0.5 , 0.25])

***Adding***

In [49]:
plus4 = myArray + 4

In [50]:
plus4

array([11,  6,  5])

***Subtracting***

In [51]:
minus4 = myArray - 4

In [52]:
minus4

array([ 3, -2, -3])

____________
### Page 6 - Indexing on Arrays

In [54]:
myArray[0]

7

**Accessing Multiple Numbers in an Array**

In [55]:
myArray[0:3]

array([7, 2, 1])

In [56]:
myArray[1:]

array([2, 1])

____________
### Page 7 - Creating Matrices with Arrays

In [57]:
myMatrix = np.array([[8, 9], [5, 4]])

In [58]:
myMatrix

array([[8, 9],
       [5, 4]])

**Matrix of all Ones**

In [60]:
all1sMatrix = np.ones((7, 2))

In [61]:
all1sMatrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**Matrix of all Zeros**

In [62]:
all0sMatrix = np.zeros((7, 2))

In [63]:
all0sMatrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**Random Matrix**

In [64]:
randomMatrix = np.random.random((7, 2))

In [65]:
randomMatrix

array([[0.39621425, 0.8537512 ],
       [0.79635674, 0.64363511],
       [0.27890575, 0.4854065 ],
       [0.31520726, 0.4807759 ],
       [0.82594468, 0.56108173],
       [0.17246225, 0.42197211],
       [0.12372615, 0.6389455 ]])

____________
### Page 8 - Matrix Arithmetic and Aggregation

**Arithmetic**

In [66]:
randomMatrix + all1sMatrix

array([[1.39621425, 1.8537512 ],
       [1.79635674, 1.64363511],
       [1.27890575, 1.4854065 ],
       [1.31520726, 1.4807759 ],
       [1.82594468, 1.56108173],
       [1.17246225, 1.42197211],
       [1.12372615, 1.6389455 ]])

**Aggregation**

In [67]:
myMatrix.min()

4

In [69]:
myMatrix.max()

9

In [70]:
myMatrix.sum()

26

In [71]:
myMatrix.mean()

6.5

In [72]:
myMatrix.std()

2.0615528128088303

____________
### Page 9 - Matrix Indexing

In [73]:
myMatrix[0,1]

9

____________
### Page 10 - Aggregating Matrix Values Across Columns and Rows

**find the largest number in the columns**

In [74]:
myMatrix.max(axis = 0)

array([8, 9])

**find the largest number in the rows**

In [75]:
myMatrix.max(axis = 1)

array([9, 5])

____________
### Page 11 - Manipulating Matrices

**Transposing**

In [77]:
all1sMatrix.T

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

**Reshaping**

In [78]:
all1sMatrix.reshape(14,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

***Reshaping to intentionally get an error***

In [81]:
# all1sMatrix.reshape(3,5)

*Commented out after getting error:*

ValueError                                Traceback (most recent call last)
/var/folders/zg/fxyw2v_910lgtrr94rf2vw0c0000gs/T/ipykernel_44358/3367259243.py in <module>
----> 1 all1sMatrix.reshape(3,5)

ValueError: cannot reshape array of size 14 into shape (3,5)